# Generated by Django 4.1.9 on 2023-07-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0066_iprange_mark_utilized'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_bgp', '0029_netbox_bgp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='assigned_object_id',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='assigned_object_type',
            field=models.ForeignKey(default='', limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualchassis')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together={('assigned_object_type', 'assigned_object_id', 'local_address', 'local_as', 'remote_address', 'remote_as')},
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device',
        ),
    ]
